audit_header: false
title: VA Real Estate Video Blog
description: >-
  Our mission at 719 Lending is to be your best resource for Colorado Springs
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from 719 Lending.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Timothy Chase
  title:
  license_number: NMLS 868175
  about_markdown: >-
    Tim Chase was born in Canon City, Colorado and has lived in Southern
    Colorado for most of his life. Currently living in Colorado Springs, Tim has
    many years of Real Estate finance experience. Although Mortgages take up
    most of the day, after work you can find Tim and his family on a quick hike
    or bicycle ride through local trails. Tim has received many sales and
    leadership accolades but none can compare to his desire to be the best
    father and a husband he can be.
  market: Colorado Springs
  brand: 719 Lending
  brand_license_number: NMLS ID 1601989
  brokerage:
  address: '108 E St Vrain St #10<br>Colorado Springs, CO 80903'
  phone: (719) 231-4893
  phone_type:
  phone2:
  phone2_type:
  email: Tchase@719Lending.com
  url: 'http://www.719lending.com'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: Have a VA Question?
    CTA_text: We specialize on helping Veterans buying homes and applying for loans.
    CTA_link_text: Ask Us
    CTA_url: /contact/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Need a VA loan?
    CTA_text2: Get Qualified with the help of our expertise.
    CTA_link_text2: Apply Now
    CTA_url2: 'https://timchase.floify.com/apply-now'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/719Lending/'
  linkedin_url: 'https://www.linkedin.com/company/719lending/'
  youtube_url: 'https://www.youtube.com/channel/UCJYomS4Y8efCtMqFa3GdESA'
  twitter_url:
  instagram_url: 'https://www.instagram.com/719_lending/'
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Colorado Springs Real Estate Podcast with Timothy Chase
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Colorado
    Springs Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    Colorado Springs Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Colorado
    Springs, home selling tips, home for sale, home buying, home buying process,
    property finder, property search, property, real estate market, estate
    agent, realestate, real estate listings, buying a house, homes for sale,
    mls, home buyer
  author: Timothy Chase
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_headshot_path: /img/headshot2.png
  hero_image: /img/soldiers.png
  logo_width_number: 30
  hero_text: VA Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#286798'
  theme_color: '#222222'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 2px
  shadow_color: 'rgba(0, 0, 0, 0.5)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'